### PR TITLE
Print float values as well

### LINKED ISSUE #3: Handle floats
The example in the readme is wrong. `4602678819172646912` should be `0.5`. Should probably just show all the ways the value can be interpreted.

### PR DESCRIPTION
**Pull request by mattprecious**
Closes #3

### CODE REVIEW

File: protogram/src/commonMain/kotlin/com/mattprecious/protogram/protogram.kt [hunk 1]
```diff
@@ -22,7 +22,12 @@ private fun ProtoReader.readNodes(): List<Node> {
 
       val nodeValue = when (encoding) {
         VARINT -> readVarint64().toString()
-        FIXED64 -> readFixed64().toString()
+        FIXED64 -> {
+          val long = readFixed64()
+          val float = Double.fromBits(long)
```
Comment (mattprecious) [inline protogram/src/commonMain/kotlin/com/mattprecious/protogram/protogram.kt]: Should probably just call this `double`
